config/routes.rb
Rails.application.routes.draw do
    root to: 'visitors#index'
    devise_for :users

    resources :users do
        get 'notifications'
    end

    resources :userdata
    resources :search
    resources :reviews

    match 'search' => 'search#index', via: 'post'
    match 'search/show/' => 'search#show', as: :search_show, via: 'get'
    match 'user/:id' => 'users#destroy', as: :destroy_user, via: 'delete'
    match 'user/:id/add_friend' => 'users#add_friend', as: :add_friend, via: 'get'
    match 'user/:id/accept_friend' => 'users#accept_friend', as: :accept_friend, via: 'get'
    match 'user/friends' => 'users#friends', as: :friends, via: 'get'
    match 'user/cancel_friend' => 'users#cancel_friend', as: :cancel_friend, via: 'delete'
    match 'user/cancel_request' => 'users#cancel_request', as: :cancel_request, via: 'delete'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    before_action :set_session, only: [:index, :show]
    before_action :validate_search, only: [:index]
    require 'set'

    def index
        @search = session[:search]
        @radius = session[:radius]
        type = params[:type]
        page_token = params[:page_token]
        results = GoogleApi.text_search(@search)
        data = GoogleApi.nearby_search(results, @radius, page_token, type)
        @results = data['results']
        @types = get_types(@results)
        @next_page_token = data['next_page_token']
        @origin_id = results['place_id']
        @map = GoogleApi.get_map(@origin_id, @origin_id)
    end

    def show
        @place_id = session[:place_id]
        @origin_id = params[:origin_id]
        result = GoogleApi.place_details(@place_id)
        @name = result['name']
        @formatted_number = result['formatted_phone_number']
        @formatted_address = result['formatted_address']
        @map = GoogleApi.get_map(@origin_id, @place_id)
        @weekday_text = get_weekday_text(result['opening_hours'])
        @photos = get_photos(result['photos'])

        @reviews = Review.where("place_id = ?", session[:place_id])
        @review = Review.new
        @count = @reviews.count
        @stars = get_stars(@reviews)
    end

    private

    def set_session
        session[:search] = params[:search] if params[:search]
        session[:radius] = params[:radius] if params[:radius]
        session[:place_id] = params[:place_id] if params[:place_id]
    end

    def validate_search
        if session[:search].empty? or session[:radius].empty?
            redirect_to :back, alert: 'Preencha todos os campos' and return
        end
    end

    def get_types(results)
        types = SortedSet.new
        results.each do |result|
            result['types'].each do |type|
                types.add(type)
            end
        end
        return types
    end

    def get_weekday_text(opening_hours)
        if opening_hours
            weekday_text = opening_hours['weekday_text']
        else
            weekday_text = ['sem informação']
        end
        return weekday_text
    end

    def get_photos(elements)
        photos = []
        if elements
            elements.each do |element|
                photos << GoogleApi.place_photos(element['photo_reference'])
            end
        end
        return photos
    end

    def get_stars(reviews)
        stars = 0.0
        reviews.each do |review|
            stars = stars + review.rate
        end
        return stars
    end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_search.html.erb
<b>Faça uma busca:</b>

<%= form_tag search_index_path, method: :get, class: "form-inline" do %>

    <div class="form-group">
        <%= text_field_tag :search, nil, placeholder: 'Onde você está? (ex: endereço, bairro, local, estabelecimento, etc...)', :size => 60, class: 'form-control' %>
        <%= text_field_tag :radius, nil, placeholder: 'Informe o raio de busca (em metros)',:size => 30, class: 'form-control' %>
    </div>

    <%= button_to 'Buscar', nil, class: 'btn btn-primary' %>

<% end %>

app/views/search/index.html.erb
<h4><span class="glyphicon glyphicon-search"></span> Resultado da busca:</h4>

<div class="text-center">
    <img src=<%= @map %> class="thumbnail">
    Verifique se você selecionou este local (caso contrário refaça a busca com mais detalhes)
</div>

<h4><span class="glyphicon glyphicon-filter"></span> Filtros:</h4>

<% @types.each do |type| %>

    <%= link_to (t type), search_index_path(:search => @search, :radius => @radius, :type => type), class: 'label label-primary' %>

<% end %>

<%= link_to 'mostrar todos os resultados', search_index_path(:search => @search, :radius => @radius, :type => 'all'), class: 'label label-success' %>

<table class="table table-hover">

    <tbody>

    <% @results.each do |result| %>

        <tr>
            <td width="50"><img src=<%= result['icon'] %>></td>

            <td>
                <h5>
                    <%= link_to result['name'], search_show_path(:origin_id => @origin_id, :place_id => result['place_id']) %>
                    <br>
                    <small><%= result['vicinity'] %></small>
                </h5>

                <% result['types'].each do |type| %>
                    <span class='label label-info'><%= t type %></span>
                <% end %>

                <% if result['opening_hours'] != nil %>
                    <span class='label label-success'><%= 'aberto agora' if result['opening_hours']['open_now'] %></span>
                <% end %>
            </td>
        </tr>

    <% end %>

    </tbody>

</table>

<%= link_to 'Voltar', :back, class: 'btn btn-default' %>

<% if @next_page_token %>

    <%= link_to 'Próxima Página', search_index_path(:page_token => @next_page_token), class: 'btn btn-primary' %>

<% end %>

app/views/search/show.html.erb
<div class="row container">
    <h2><%= @name %></h2>
    <p>
        <%= link_to 'Adicionar aos Favoritos', new_userdatum_path(:name => @name, :place_id => @place_id), class: 'btn btn-primary' if user_signed_in? %>
        <%= link_to 'Voltar', 'javascript:history.go(-1);', class: 'btn btn-default' %>
    </p>

    <div class="col-md-4">

        <h4><span class="glyphicon glyphicon-map-marker"></span> Endereço: </h4>
        <address><%= @formatted_address %></address>

        <br>

        <h4><span class="glyphicon glyphicon-earphone"></span> Telefone:</h4>
        <% if @formatted_number %>

            <address><%= @formatted_number %></address>

        <% else %>

            Nenhum número disponível<br>

        <% end %>

        <br>

        <h4><span class="glyphicon glyphicon-time"></span> Horário de Funcionamento:</h4>
        <% @weekday_text.each do |day| %>
            <address><%= day %></address>
        <% end %>

        <br>

        <h4><span class="glyphicon glyphicon-star"></span> Avaliação:</h4>
        <% if @count == 0 %>
            <address>Sem Avaliação</address>
        <% else %>
            <address><%= (@stars/@count).round(1) %> / 5.0</address>
        <% end %>

        <br>

        <% if user_signed_in? %>
            <%= render :partial => 'reviews/form' %>
        <% end %>

    </div>

    <div class="col-md-8">
        <div id="myCarousel" class="carousel slide" data-ride="carousel" style="background-color: black">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <% (1..@photos.size).each do |i| %>
                    <li data-target="#myCarousel" data-slide-to="<%= i %>"></li>
                <% end %>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox" style="width:100%; height: 480px !important;">
                <div class="item active">
                    <img src=<%= @map %>>
                </div>
                <% @photos.each do |photo| %>
                    <div class="item">
                        <img src=<%= photo %>>
                    </div>
                <% end %>

            </div>

            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <br>
        <h4><span class="glyphicon glyphicon-comment"></span> Comentários:</h4>
        <table class="table table-hover">
            <% if @reviews.empty? %>

                Nenhum comentário ainda

            <% else %>

                <tbody>
                <% @reviews.each do |review| %>
                    <% if User.exists?(review.user_id) %>
                        <tr>
                            <td width="100"><img src=<%= GravatarApi.small_photo(User.find(review.user_id).email) %>>
                            </td>
                            <td>
                                <h5>
                                    <%= link_to User.find(review.user_id).name, user_path(id: User.encrypt(review.user_id)) %>
                                    <br>
                                    <small>última atualização: <%= review.updated_at.strftime('%d/%m/%Y %H:%M') %></small>
                                </h5>

                                <%= review.comment %>
                            </td>
                            <td class="text-center">
                                <b>Avaliação</b>
                                <h3><%= review.rate %></h3>
                            </td>

                            <% if current_user %>
                                <% if review.user_id == current_user.id or current_user.admin %>
                                    <td class="text-right">
                                        <%= link_to 'Editar', edit_review_path(review), class: 'btn btn-warning' %>
                                        <%= link_to 'Apagar', review, method: :delete, data: {confirm: 'Você tem certeza?'}, class: 'btn btn-danger' %>
                                    </td>
                                <% end %>
                            <% else %>
                                <th colspan="4"></th>
                            <% end %>
                        </tr>
                    <% else %>
                        <% review.destroy %>
                    <% end %>
                <% end %>
                </tbody>

            <% end %>
        </table>
    </div>
</div>