config/routes.rb
Rails.application.routes.draw do
    root to: 'visitors#index'
    devise_for :users

    resources :users do
        get 'notifications'
    end

    resources :userdata
    resources :search
    resources :reviews

    match 'search' => 'search#index', via: 'post'
    match 'search/show/' => 'search#show', as: :search_show, via: 'get'
    match 'user/:id' => 'users#destroy', as: :destroy_user, via: 'delete'
    match 'user/:id/add_friend' => 'users#add_friend', as: :add_friend, via: 'get'
    match 'user/:id/accept_friend' => 'users#accept_friend', as: :accept_friend, via: 'get'
    match 'user/friends' => 'users#friends', as: :friends, via: 'get'
    match 'user/cancel_friend' => 'users#cancel_friend', as: :cancel_friend, via: 'delete'
    match 'user/cancel_request' => 'users#cancel_request', as: :cancel_request, via: 'delete'
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise  :database_authenticatable, :registerable,
            :recoverable, :rememberable, :trackable, :validatable
    
    include Obfuscate

    def to_param
        encrypt id
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        @users = User.all
    end

    def show
        @user = User.find User.decrypt(params[:id])
        @userdata = Userdatum.where(:user_id => @user.id)
        @reviews = Review.where("user_id = ?", @user.id)
        @friends = Friend.where("user_id = ?", @user.id).where("status = ?", 2)
        @gravatar = GravatarApi.big_photo(@user.email)
    end

    def destroy
        @user = User.find User.decrypt(params[:id])
        @user.destroy
        redirect_to users_path, :flash => {:notice => "Remoção com sucesso!"}
    end

    def add_friend
        @user = User.find current_user.id
        @friend = User.find User.decrypt params[:id]

        checkFriend = Friend.where("user_id = ?", @user.id).where("friend_id = ? ", @friend.id).first
        if @user.id == @friend.id
          redirect_to :back, :alert => "Este é você!"
          return
        end

        if !checkFriend
            @friendship = Friend.new(user_id: @user.id, friend_id: @friend.id, status: 1)

            if @friendship.save!
                redirect_to user_path(id: User.encrypt(@friend.id)), :flash => {:notice => "Solicitação feita com sucesso."}
            else
                redirect_to :back, :alert => "Problema ao solicitar amizade."
            end
        else
            redirect_to :back, :alert => "Você ja solicitou essa amizade."
        end
    end

    def notifications
        @user = current_user
        @friends = Friend.where("friend_id = ?", @user.id)
        @friendRequest = Array.new

        @friends.each do |friend|
            if friend.status == 1
                @friendRequest << friend
            end
        end
    end

    def accept_friend
        @user = current_user
        @friend = User.find User.decrypt(params[:friend_id])

        @friendship1 = Friend.where("user_id = ?", @friend.id).where("friend_id = ?", @user.id)[0]
        @friendship1.status = 2;

        @friendship2 = Friend.new(user_id: @user.id, friend_id: @friend.id, status: 2)

        if @friendship1.save! and @friendship2.save!
            redirect_to user_notifications_path(user_id: User.encrypt(current_user.id)), :flash => {:notice => "Solicitação aceita com sucesso!"}
        else
            redirect_to :back, :alert => "Problema ao aceitar amizade amizade."
        end
    end

    def friends
        @user = User.find current_user.id
        @friends = Friend.where("user_id = ?", @user.id).where("status = ?", 2)
    end

    def cancel_friend
        @user = User.find current_user.id
        @friend = User.find User.decrypt(params[:friend_id])

        @friendship1 = Friend.where("user_id = ?", @user.id).where("friend_id = ?", @friend.id).first
        @friendship2 = Friend.where("user_id = ?", @friend.id).where("friend_id = ?", @user.id).first

        if @friendship1.delete and @friendship2.delete
            redirect_to :back, :flash => {:notice => "Remoção com sucesso!"}
        else
            redirect_to :back, :alert => "Problema ao cancelar amizade amizade."
        end
    end

    def cancel_request
        @user = User.find current_user.id
        @friend = User.find User.decrypt(params[:friend_id])
        @friendship2 = Friend.where("user_id = ?", @friend.id).where("friend_id = ?", @user.id).first

        if @friendship2.delete
            redirect_to :back, :flash => {:notice => "Remoção com sucesso!"}
        else
           redirect_to :back, :alert => "Problema ao cancelar amizade amizade."
        end
    end
end

app/views/users/_friends_list.html.erb
<h4><span class="glyphicon glyphicon-user"></span> Amigos</h4>

<% if @friends.empty? %>

    Nenhum amigo

<% else %>

    <% @friends.each do |friend| %>

        <% if User.exists?(friend.friend_id) %>

            <div class="col-md-2 text-center">
                <% user = User.find(friend.friend_id) %>

                <%= render user %>

                <% if @user == current_user %>
                    <%= link_to 'Cancelar amizade', cancel_friend_path(friend_id: User.encrypt(friend.friend_id)), method: :delete, data: {confirm: 'Você tem certeza?'}, class: 'btn btn-danger pull' %>
                <% end %>
            </div>

        <% end %>

    <% end %>

<% end %>

app/views/users/_user.html.erb
<img src=<%= GravatarApi.mid_photo(user.email) %> class="thumbnail">

<%= link_to user.name, user %>

<br>

<% if current_user.admin %>
    <%= link_to "Cancelar conta", destroy_user_path(user), :data => {:confirm => "Você tem certeza?"}, :method => :delete, :class => 'btn btn-danger' %>
<% end %>

app/views/users/add_friend.html.erb
<h1>Solicitação de amizade enviada com sucesso!</h1>

app/views/users/friends.html.erb
<%= render :partial => 'friends_list' %>

app/views/users/index.html.erb
<h4><span class="glyphicon glyphicon-user"></span> Usuários</h4>

<div class="row text-center">

    <% @users.each do |user| %>

        <div class="col-md-2">

            <%= render user %>

            <br>

        </div>

    <% end %>

</div>

app/views/users/notifications.html.erb
<h4><span class="glyphicon glyphicon-inbox"></span> Notificações</h4>
<table class="table table-hover">
    <% if @friendRequest.empty? %>

        Nenhuma notificação

    <% else %>
        <thead>
        <tr>
            <th>Solicitante</th>
            <th>Solicitado</th>
            <th colspan="3"></th>
            <th colspan="4"></th>
        </tr>
        </thead>

        <tbody>
        <% @friendRequest.each do |friend| %>
            <tr>
                <% if User.exists?(friend.user_id) %>
                    <td><%= User.find(friend.user_id).name %></td>
                    <td><%= User.find(friend.friend_id).name %></td>
                    <td><%= link_to 'Aceitar', accept_friend_path(id: User.encrypt(current_user.id), friend_id: User.encrypt(friend.user_id)), class: 'btn btn-success' %></td>
                    <td><%= link_to 'Recusar convite', cancel_request_path(friend_id: User.encrypt(friend.user_id)), method: :delete, data: {confirm: 'Você tem certeza?'}, class: 'btn btn-danger' %></td>
                <% else %>
                    <% friend.destroy %>
                <% end %>
            </tr>
        <% end %>
        </tbody>

    <% end %>
</table>

app/views/users/show.html.erb
<h4><span class="glyphicon glyphicon-globe"></span> Perfil Público</h4>

<div class="row">
    <div class="col-md-3">
        <br>
        <img src=<%= @gravatar %> class="thumbnail">
        <br>
    </div>

    <div class="col-md-9">
        <br>
        <h2><%= @user.name if @user.name %></h2>
        <h5><%= @user.email if @user.email %></h5>
        <h5><%= link_to "Adicionar amigo", add_friend_path, {class: "btn btn-primary"} %></h5>
    </div>
</div>

<br>

<%= render :partial => 'userdata/userdata_list' %>

<br>

<%= render :partial => 'reviews/review_list' %>

<br>

<%= render :partial => 'users/friends_list' %>