config/routes.rb
Rails.application.routes.draw do
    root to: 'visitors#index'
    devise_for :users

    resources :users do
        get 'notifications'
    end

    resources :userdata
    resources :search
    resources :reviews

    match 'search' => 'search#index', via: 'post'
    match 'search/show/' => 'search#show', as: :search_show, via: 'get'
    match 'user/:id' => 'users#destroy', as: :destroy_user, via: 'delete'
    match 'user/:id/add_friend' => 'users#add_friend', as: :add_friend, via: 'get'
    match 'user/:id/accept_friend' => 'users#accept_friend', as: :accept_friend, via: 'get'
    match 'user/friends' => 'users#friends', as: :friends, via: 'get'
    match 'user/cancel_friend' => 'users#cancel_friend', as: :cancel_friend, via: 'delete'
    match 'user/cancel_request' => 'users#cancel_request', as: :cancel_request, via: 'delete'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @review = Review.new
    end

    def create
        @review = Review.new review_params
        @review.user_id = current_user.id
        @review.place_id = session[:place_id]

        alreadyReviewd = nil
        alreadyReviewd = Review.where("user_id = ? AND place_id = ?", current_user.id, session[:place_id]).first

        if alreadyReviewd.nil? and @review.save!
            redirect_to search_show_path, notice: 'Comentario adiciondo com sucesso'
        else
            redirect_to search_show_path, alert: 'Erro! Você ja comentou sobre esse local'
        end
    end

    def edit
        @review = Review.find(params[:id])
    end

    def update
        @review = Review.find(params[:id])
        respond_to do |format|
            if @review.update(review_params)
                format.html {redirect_to search_show_path, notice: 'Comentário atualizado com sucesso'}
                format.json {render :show, status: :ok, location: @review}
            else
                format.html {render :edit}
                format.json {render json: @review.errors, status: :unprocessable_entity}
            end
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        respond_to do |format|
            format.html {redirect_to search_show_path, notice: 'Comentário apagado com sucesso'}
            format.json {head :no_content}
        end
    end

    private

    def review_params
        params.require(:review).permit(:rate, :user_id, :place_id, :comment)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
    <% if @review.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

            <ul>
                <% @review.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :comment %>
        <%= f.text_area :comment, rows: 3, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label 'Avaliação' %>
        <%= f.select(:rate, get_ratings, {:selected => @review.rate}, {:class => 'form-control'}) %>
    </div>

    <div class="actions">
        <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/reviews/_review_list.html.erb
<h4><span class="glyphicon glyphicon-comment"></span> Análises</h4>
<table class="table table-hover">
    <% if @reviews.empty? %>

        Nenhuma análise

    <% else %>

        <thead>
        <tr>
            <th colspan="1"></th>
            <th class="text-left">Local e Comentário Público</th>
            <th colspan="3">
        </tr>
        </thead>

        <tbody>
        <% @reviews.each do |review| %>
            <tr>
                <% result = GoogleApi.place_details(review.place_id) %>
                <td width="50"><img src=<%= result['icon'] %>></td>
                <td>
                    <h5>
                        <%= link_to result['name'], search_show_path(:place_id => review.place_id) %>
                        <br>
                        <small><%= result['vicinity'] %></small>
                    </h5>
                    <%= review.comment %>

                </td>
                <td class="text-center">
                    <b>Avaliação</b>
                    <h3><%= review.rate %></h3>
                </td>

                <% if current_user %>
                    <% if review.user_id == current_user.id or current_user.admin %>
                        <td class="text-right">
                            <%= link_to 'Editar', edit_review_path(review), class: 'btn btn-warning' %>
                            <%= link_to 'Apagar', review, method: :delete, data: {confirm: 'Você tem certeza?'}, class: 'btn btn-danger' %>
                        </td>
                    <% end %>
                <% else %>
                    <th colspan="4"></th>
                <% end %>
            </tr>
        <% end %>
        </tbody>

    <% end %>
</table>

app/views/reviews/edit.html.erb
<h3>Editar comentário público</h3>

<%= render 'form', review: @review, label: "Salvar modificações" %>

<%= link_to 'Voltar', :back, class: "btn btn-default" %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h3>Novo comentário público</h3>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>