config/routes.rb
Rails.application.routes.draw do
    root to: 'visitors#index'
    devise_for :users

    resources :users do
        get 'notifications'
    end

    resources :userdata
    resources :search
    resources :reviews

    match 'search' => 'search#index', via: 'post'
    match 'search/show/' => 'search#show', as: :search_show, via: 'get'
    match 'user/:id' => 'users#destroy', as: :destroy_user, via: 'delete'
    match 'user/:id/add_friend' => 'users#add_friend', as: :add_friend, via: 'get'
    match 'user/:id/accept_friend' => 'users#accept_friend', as: :accept_friend, via: 'get'
    match 'user/friends' => 'users#friends', as: :friends, via: 'get'
    match 'user/cancel_friend' => 'users#cancel_friend', as: :cancel_friend, via: 'delete'
    match 'user/cancel_request' => 'users#cancel_request', as: :cancel_request, via: 'delete'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Editar conta', edit_user_registration_path %></li>
  <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Entrar', new_user_session_path %></li>
  <li><%= link_to 'Registrar', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Usuários', users_path %></li>
  <li><%= link_to 'Notificações', user_notifications_path(user_id: User.encrypt(current_user.id)) %></li>
  <li><%= link_to 'Amigos', friends_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'Sobre', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Exploracao Bairros" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Exploracao Bairros" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body>
<header>
    <%= render 'layouts/navigation' %>
</header>
<main role="main" style="background-color: white">
    <div class="container">
        <%= render 'layouts/messages' %>
        <%= yield %>
    </div>
</main>
</body>
</html>